"""M5 — Export: package the calibrated config into a runnable bundle.

Emits a self-contained `<project>/export/` directory: the compiled system prompt
(the behavior, provider-agnostic), the spec/rubric/tests for the record, an
Ollama `Modelfile` so `ollama create` runs the calibrated AI locally, a
zero-dependency runner, and a README. Fully deterministic — no engine calls.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

import yaml

from .compile import rag_config, render_system_prompt, rubric
from .engines.base import parse_engine_spec
from .models import Project
from .store import atomic_write_text

DEFAULT_LOCAL_BASE = "qwen2.5:14b"

_RUN_PY = '''#!/usr/bin/env python3
"""Run the calibrated AI locally via Ollama (standard library only).

Usage:
    python run.py "your question"        # or:  echo "..." | python run.py

Requires Ollama running locally with the base model pulled:
    ollama pull __BASE_MODEL__
"""
import json
import sys
import urllib.request
from pathlib import Path

BASE_MODEL = "__BASE_MODEL__"
HOST = "http://localhost:11434"


def main() -> None:
    system = (Path(__file__).parent / "system_prompt.txt").read_text()
    question = " ".join(sys.argv[1:]).strip() or sys.stdin.read().strip()
    if not question:
        print('usage: python run.py "your question"', file=sys.stderr)
        sys.exit(1)
    payload = {
        "model": BASE_MODEL,
        "stream": False,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": question},
        ],
    }
    req = urllib.request.Request(
        HOST + "/api/chat",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req) as resp:
        print(json.loads(resp.read())["message"]["content"])


if __name__ == "__main__":
    main()
'''


@dataclass
class ExportResult:
    bundle_dir: str
    name: str
    base_model: str
    files: list[str]


def _slug(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s or "calibrated-ai"


def _modelfile(base_model: str, system_prompt: str) -> str:
    safe = system_prompt.replace('"""', '\\"\\"\\"')
    return (
        "# Calibrated AI — generated by ai-calibrator\n"
        f"FROM {base_model}\n\n"
        f'SYSTEM """\n{safe}"""\n'
    )


def _readme(name: str, base_model: str) -> str:
    return f"""# Calibrated AI — {name}

Generated by **ai-calibrator**. The behavior lives in `system_prompt.txt`
(provider-agnostic). `spec.yaml`, `rubric.yaml`, and `tests.jsonl` are the record
of what it was calibrated to.

## Run locally with Ollama
```bash
ollama pull {base_model}
ollama create {name} -f Modelfile
ollama run {name}
```

## Run programmatically (zero dependencies, uses local Ollama)
```bash
python run.py "your question"
```

## Use with any provider
Apply `system_prompt.txt` as the **system prompt** on the model of your choice
(Claude / OpenAI / local). Evaluate changes against `rubric.yaml` + `tests.jsonl`.

> Note: the simple `run.py` runner is system-prompt only — it does not perform
> retrieval. To ground answers in your documents, wire the index described in
> `rag.config.yaml` into your runtime.
"""


def export_bundle(project: Project, *, project_dir: str | Path, name: str | None = None) -> ExportResult:
    """Write the runnable bundle to <project_dir>/export/ and return its summary."""
    spec = project.spec
    if spec is None:
        raise ValueError("Nothing to export — run `calibrate compile` first.")

    bundle_name = _slug(name or project.name)
    model, provider = parse_engine_spec(project.engines.subject)
    # The system prompt is provider-agnostic; the Modelfile applies it to a LOCAL
    # base. If the subject is an Ollama model, use it; otherwise default local base.
    base = model if provider == "ollama" else DEFAULT_LOCAL_BASE
    system = render_system_prompt(spec)

    out = Path(project_dir) / "export"
    out.mkdir(parents=True, exist_ok=True)
    files: list[str] = []

    def _write(fn: str, content: str) -> None:
        atomic_write_text(out / fn, content)
        files.append(f"export/{fn}")

    _write("system_prompt.txt", system)
    _write("spec.yaml", yaml.safe_dump(spec.model_dump(mode="json"), sort_keys=False))
    _write("rubric.yaml", yaml.safe_dump(rubric(spec), sort_keys=False))
    _write("rag.config.yaml", yaml.safe_dump(rag_config(spec), sort_keys=False))
    _write("tests.jsonl", "".join(json.dumps(t.model_dump(mode="json")) + "\n" for t in project.tests))
    _write("Modelfile", _modelfile(base, system))
    _write("run.py", _RUN_PY.replace("__BASE_MODEL__", base))
    _write("README.md", _readme(bundle_name, base))

    return ExportResult(bundle_dir=str(out), name=bundle_name, base_model=base, files=files)
